version: '3'
services:
  neo4j:
    image: neo4j:3.5.7
    container_name: neo4j
    restart: always
    network_mode: "bridge"
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j:/data
    environment:
      - NEO4J_AUTH=none
      #neo4j/neo4j
volumes:
  neo4j:
