services:
  samba:
    image: dockurr/samba
    container_name: samba
    environment:
      NAME: "Data"
      USER: "cq"
      PASS: "123456"
    ports:
      - 445:445
    volumes:
      - ./data:/storage
