version: '3'
services:
    dnsmasq:
      image: jpillora/dnsmasq:1.1.0
      container_name: dnsmasq
      restart: always
      ports:
        - 53:53/udp
        - 5380:8080
      volumes:
        - ./dnsmasq.conf:/etc/dnsmasq.conf
      logging:
        driver: "json-file"
        options:
          max-size: "100m"
      environment:
        HTTP_USER: foo
        HTTP_PASS: bar
