version: '3'
services:
    zabbix-agent:
      image: zabbix/zabbix-agent:alpine-4.2.0
      container_name: zabbix-agent
      privileged: true
      restart: always
      hostname: pc-001
      network_mode: "bridge"
      ports:
        - 10050:10050
      volumes:
        - ./modules:/var/lib/zabbix/modules
      environment:
        ZBX_HOSTNAME: 'pc-001'
        ZBX_SERVER_HOST: '192.168.199.124'
        ZBX_SERVER_PORT: 10051
        #ZBX_PASSIVE_ALLOW: 'true'
        #ZBX_PASSIVESERVERS: 'server,proxy'
        #ZBX_ACTIVE_ALLOW: 'true'
        #ZBX_ACTIVESERVERS: 'server:10061,proxy:10072'
        #ZBX_LOADMODULE: 'dummy1.so,dummy2.so'
        #ZBX_DEBUGLEVEL: 3
        #ZBX_TIMEOUT: 3
