version: '3'
services:
    scope:
      image: weaveworks/scope:1.9.1
      network_mode: "host"
      pid: "host"
      privileged: true
      ports:
        - "4040:4040"
      labels:
        - "works.weave.role=system"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:rw"
      command:
        - "--probe.docker=true"
