version: '3'
services:
    rabbitmq:
      image: rabbitmq:3.7.12-management-alpine
      container_name: some-rabbit
      restart: always
      hostname: my-rabbit
      network_mode: "bridge"
      ports:
        - 5672:5672
        - 15672:15672
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
