version: '3'
services:
    gitlab:
      image: gitlab/gitlab-ce:10.3.5-ce.0
      container_name: gitlab
      restart: always
      hostname: gitlab.example.com
      ports:
        - 80:80
      volumes:
        - ./config:/etc/gitlab
        - ./logs:/var/log/gitlab
        - ./data:/var/opt/gitlab
      environment:
        TZ: Asia/Shanghai
        GITLAB_OMNIBUS_CONFIG: |
            external_url 'http://45.77.191.127'
            gitlab_rails['time_zone'] = 'Asia/Shanghai'
            gitlab_rails['smtp_enable'] = true
            gitlab_rails['smtp_address'] = 'smtp.163.com'
            gitlab_rails['smtp_port'] = 465
            gitlab_rails['smtp_user_name'] = 'chenq182@163.com'
            gitlab_rails['smtp_password'] = 'llysc1s1kr'
            gitlab_rails['smtp_authentication'] = 'login'
            gitlab_rails['smtp_enable_starttls_auto'] = true
            gitlab_rails['smtp_tls'] = true
            gitlab_rails['gitlab_email_from'] = 'chenq182@163.com'

