version: '3'
services:
  mongo-express:
    image: mongo-express:0.49.0
    container_name: mongo-express
    restart: always
    network_mode: "bridge"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: guest
      ME_CONFIG_BASICAUTH_PASSWORD: guest
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      #ME_CONFIG_MONGODB_ENABLE_ADMIN: 'false'
      #ME_CONFIG_MONGODB_AUTH_DATABASE: db
      #ME_CONFIG_MONGODB_AUTH_USERNAME: user
      #ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: '106.12.2.90'
