version: '3'
services:
  consul:
    image: consul:1.6.1
    container_name: consul
    restart: always
    network_mode: "host"
    ports:
      - 8300-8302:8300-8302
      - 8500:8500
      - 8600:8600
    environment:
      TZ: Asia/Shanghai
