version: '3'
services:
  nginx:
    image: nginx:1.16.0-alpine
    container_name: some-nginx
    #restart: always
    network_mode: "bridge"
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
