version: '3'
services:
    jenkins:
      build: .
      image: chenq/jenkins:latest
      container_name: jenkins
      restart: always
      network_mode: "bridge"
      ports:
        - 8080:8080
        - 50000:50000
        - 80:80
        - 10080:10080
      volumes:
        - home:/var/jenkins_home
      environment:
        TZ: Asia/Shanghai
        #JAVA_OPTS: -Djenkins.install.runSetupWizard=false
volumes:
    home:
