version: '3'
services:
    httpd:
      image: httpd:2.4.33-alpine
      container_name: httpd
      #restart: always
      network_mode: "bridge"
      ports:
        - "8080:80"
      volumes:
        - ./ROOT:/usr/local/apache2/htdocs
        #- ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
