version: '3'
services:
    mysql:
      image: mysql:5.7.20
      container_name: some-mysql
      #restart: always
      network_mode: "bridge"
      ports:
        - "3306:3306"
      volumes:
        - mysql:/var/lib/mysql
        - /etc/localtime:/etc/localtime:ro
      environment:
        MYSQL_ROOT_PASSWORD: '123456'
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
volumes:
    mysql:
