version: '3'
services:
  shadowsocks:
    image: mritd/shadowsocks
    container_name: ssclient
    restart: always
    network_mode: "bridge"
    ports:
      - 1080:1080
    command: -m "ss-local" -s "-s 8.6.8.152 -p 2017 -b 0.0.0.0 -l 1080 -m chacha20 -k ${SHADOWSOCKS_KEY} --fast-open"
