version: '3'
services:
    solr:
      image: solr:8.0.0-alpine
      container_name: solr
      #restart: always
      network_mode: bridge
      ports:
        - 8983:8983
      volumes:
        - solr:/opt/solr/server/solr/mycores
      entrypoint:
        - docker-entrypoint.sh
        - solr-precreate
        - test
volumes:
    solr:
